=== api-commons/api-commons/schemas/apis-io-schema.json
{
  "title": "A JSON Schema for apis.json, version 0.14",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^X-": { "type": "object" }
  },
  "definitions": {
    "maintainer": {
      "description": "The person or organization responsible for maintaining the API",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "additionalProperties": {
        "type": "string"
      }
    },
    "apis": {
      "description": "The description of the API",
      "oneOf": [
        {
          "required": [ "$ref" ],
          "properties": {
            "$ref": {
              "type": "string"
            }
          }
        },
        {
          "required": [
            "name", "description", "image", "humanURL", "urls", "contact"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "image": {
              "type": "string"
            },
            "humanUrl": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "urls": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/urls"
              }
            },
            "contact": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/contact"
              }
            },
            "meta": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/metaInformation"
              }
            }
          }
        }
      ]
    },
    "metaInformation": {
      "description": "Metadata about the API",
      "required": [
        "key", "value"
      ],
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "contact": {
      "description": "Information on contacting the API support",
      "required": [
        "type", "url"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "twitter"
          ]
        },
        "url": {
          "type": "string",
          "pattern": "^(http)|(https)://(.*)$"
        }
      }
    },
    "urls": {
      "description": "A representation of a URL",
      "required": [
        "type", "url"
      ],
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^(portal)$|^(console)$|^(signup)$|^(libraries)$|^(swagger)$|^(X-[a-z0-9\\-]*)$"
        },
        "url": {
          "type": "string",
          "pattern": "^(http)|(https)://(.*)$"
        }
      }
    },
    "tags": {
      "description": "A consistent set of tag to apply to a description",
      "pattern": "^(photo)$|^(upload)$|^(marketplace)$|^(X-[a-z0-9\\-]*)$"
    }
  },
  "required": [
    "name", "description", "type", "url", "apis", "maintainer", "tags"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the service described"
    },
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "apis": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/apis"
      }
    },
    "maintainer": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/maintainer"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/tags"
      }
    },
    "definitions": {}
  }
}

=== api-commons/api-commons/samples/sample-2.json
{
  "name": "sample-name",
  "description": "sample description",
  "type": "default",
  "url": "http://sample.com",
  "image": "http://www.sample.com/image.png",
  "apis": [
    {
      "$ref": "#/definitions/reference1"
    }
  ],
  "maintainer": [
    {
      "name": "fred meyer",
      "twitter": "https://twitter.com/foo",
      "github": "https://github.com/bar"
    }
  ],
  "tags": ["photo", "upload", "marketplace"],
  "definitions": {
    "reference1": {
      "name": "name 1",
      "description": "this can live on a remote URL",
      "image": "http://sample.com/images-1.png",
      "humanURL": "https://sample.com/repository",
      "tags": [ "photos", "reference" ],
      "urls": [
        {
          "type": "portal",
          "url": "https://sample.com/portal"
        },
        {
          "type": "console",
          "url": "https://sample.com/console"
        },
        {
          "type": "X-custom-123",
          "url": "http://sample.com/console"
        }
      ],
      "contact": [
        {
          "type": "twitter",
          "url": "https://sample.com/twitter"
        }
      ],
      "meta": [
        {
          "key": "pricing",
          "value": "Free"
        }
      ]
    }
  }
}

=== api-commons/api-commons/samples/sample-1.json
{
  "name": "sample-name",
  "description": "sample description",
  "type": "default",
  "url": "http://sample.com",
  "image": "http://www.sample.com/image.png",
  "apis": [
    {
      "name": "name 1",
      "description": "description 1",
      "image": "http://sample.com/images-1.png",
      "humanURL": "https://sample.com/repository",
      "tags": [ "photos", "reference" ],
      "urls": [
        {
          "type": "portal",
          "url": "https://sample.com/portal"
        },
        {
          "type": "console",
          "url": "https://sample.com/console"
        },
        {
          "type": "X-custom-123",
          "url": "http://sample.com/console"
        }
      ],
      "contact": [
        {
          "type": "twitter",
          "url": "https://sample.com/twitter"
        }
      ],
      "meta": [
        {
          "key": "pricing",
          "value": "Free"
        }
      ]
    }
  ],
  "maintainer": [
    {
      "name": "fred meyer",
      "twitter": "https://twitter.com/foo",
      "github": "https://github.com/bar"
    }
  ],
  "tags": ["photo", "upload", "marketplace"]
}
